### ISSUE TITLE
Transfer to the toml-lang organisation?

### ISSUE THREAD

**Issue by pradyunsg** [toml-lang/toml-test#137]
x-ref https://github.com/toml-lang/toml/issues/585

This is a question for the current maintainers/owners on this repository -- would you be willing to transfer the project into the toml-lang repository?

**Comment by arp242** [comment]
Do you have admin permissions on the toml organisation? I think that's the bit where it got stuck on before.

**Comment by pradyunsg** [comment]
Yes, I do now.  :)

**Comment by arp242** [comment]
Coolio; I unsubscribed from the "onboarding new maintainers" issue some time ago due to all the off-topic noise, so didn't see your update 😅

For what it's worth, I'd prefer the repo to be at https://github.com/toml-lang/toml-test rather than https://github.com/toml-lang/compliance – it fits better with how Go works, people are already familiar with the name "toml-test" so its more obvious it's just the same thing a a new location, and toml-lang/compliance was never really used for anything so little value in keeping that name.

Just need @BurntSushi to transfer to the toml-lang organisation; previously he said he didn't mind doing that anyway.

**Comment by BurntSushi** [comment]
I'm fine to do whatever y'all decide.

**Comment by arp242** [comment]
Can you transfer this to the `toml-lang` organisation at https://github.com/BurntSushi/toml-test/transfer @BurntSushi? Thanks!

**Comment by BurntSushi** [comment]
Done!

**Comment by arp242** [comment]
Cheers, thanks!

Seems like my permissions survived the move too; so all looks grand (I think admin permissions weren't actually needed after all? Ah well...)
