### ISSUE TITLE
`valid/float/zero.json` does not have signs on the zero

### ISSUE THREAD

**Issue by KristofferC** [toml-lang/toml-test#85]
According to the TOML spec:

> Float values -0.0 and +0.0 are valid and should map according to IEEE 754.

The TOML file `valid/float/zero.toml` has for example:

```toml
f3 = -0.0
```

but the corresponding JSON has

```json
  "f3": {
    "type": "float",
    "value": "0"
  },
```

I think the values here should have the corresponding signs as the TOML file.

**Comment by dmbaturin** [comment]
That file is even more problematic when used for the _encoder_ test. It expects the encoder to magically deduce that `{"type": "float", "value": "0"` should be formatted as "0e0". ;)

**Comment by oittaa** [comment]
Just a random passerby, but I also noticed that https://toml.io/en/v1.0.0#float states 

> Float values `-0.0` and `+0.0` are valid and should map according to IEEE 754.

**Comment by arp242** [comment]
> That file is even more problematic when used for the encoder test. It expects the encoder to magically deduce that {"type": "float", "value": "0"} should be formatted as "0e0"

You should always check if the values are semantically identical, not if the string values as they appear in the TOML file are identical. There's a bunch of values that can be expressed in multiple ways, and how exactly it should be formatted is up to the encoder.

For example all of the text for the different integer base formats (0xff, 0b01, 0o666, etc.) use decimal in the JSON files, because 0xff == 255.

0e0 equals 0, and -0 equals 0. Although the case of signed zero is a bit more nuanced because even though it's equal, it doesn't behave exactly the same in all conditions (so it does matter), but because 0 == -0 it's actually not easy to distinguish between the two with standard comparisons, so in that sense it doesn't matter what we put in the JSON file.

Some encoders may choose to always write back in a certain format (e.g. decimal), others may choose to use the same as the input format. Both are valid choices. You *could* use the JSON file to test this, but if we change "0" to "0e0" then it's less convenient for the implementations which always write floats as decimal.

So in the end it's going to be less convenient for someone, and it's just a matter of choosing *who*.

I added a note in the README for this.

**Comment by KristofferC** [comment]
I don't understand how this argument applies to 0.0 and -0.0. Those are not semantically identical and the spec even calls this out explicitly with a reference to IEEE 754. So this issue is not a question about how a number is written.

**Comment by arp242** [comment]
> Those are not semantically identical 

They're not, but they do compare to be equal:

    >>> print(0.0, -0.0, 0.0 == -0.0)
    0.0 -0.0 True

Which is how it should behave according to IEEE.

I don't see how you *can* use toml-test to test this? Because at the end of the day, it should just do "have == want"?

I mean, if it's really useful for you I don't mind changing it I guess, as it shouldn't hurt anything, but it just doesn't really seem helpful to me.

**Comment by arp242** [comment]
I took a look at Julia's tests, and with some hackery I added:

    if rel == "valid/float/zero"
		Base.print("\n\n")
		#Base.print(jsn)
		#Base.print(tml)
		Base.print(tml["signed-neg"] == jsn["signed-neg"], isequal(tml["signed-neg"], jsn["signed-neg"]))
		Base.print("\n\n")
	end

Which outputs:

    truefalse

Looking at [some docs](https://docs.julialang.org/en/v1/base/base/#Base.isequal), isequal() seems the same as ==, except with some special-fu for float-y things like NaN and -0.

So that's the missing bit: Julia *doesn't* treat them as equal.

**Comment by arp242** [comment]
Anyway, I added it to the JSON file, and I can confirm it works if I fix it manually in your toml-test-julia .jl file.

**Comment by arp242** [comment]
@KristofferC bit off-topic, but do you have some spare time to help add Julia to https://github.com/arp242/toml-test-matrix? I looked at this yesterday, but the practical problem I ran in to is that Julia seems to have a fairly slow start-up time, so `toml-test julia-decoder` takes about half a second per test on my laptop(!) I can't really figure out a way to compile a binary, but maybe I'm just missing something?

Also see: https://github.com/toml-rs/toml/discussions/616

This would also help Julia, because running the test suite easily allows me to see these type of problems much sooner for newer tests that are added; these kind of subtle "Julia does comparison of -0 and +0 a bit different than other languages" are kind of hard to predict.
